# Generated by Django 6.1.1 on 2026-10-10 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('numero_cuenta', models.IntegerField(db_column='NumeroCuenta')),
                ('porcentaje', models.IntegerField(db_column='Porcentaje', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('activo', models.BooleanField(db_column='FechaDesactivacion', default=True)),
            ],
            options={
                'db_table': 'Beneficiario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=32)),
            ],
            options={
                'db_table': 'Parentesco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=64)),
                ('valor_documento', models.CharField(db_column='ValorDocumentoIdentidad', max_length=32, unique=True)),
                ('fecha_nacimiento', models.DateField(db_column='FechaNacimiento')),
                ('email', models.EmailField(db_column='Email', max_length=254)),
                ('telefono1', models.CharField(db_column='telefono1', max_length=16)),
                ('telefono2', models.CharField(db_column='telefono2', max_length=16)),
            ],
            options={
                'db_table': 'Persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDoc',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=64)),
            ],
            options={
                'db_table': 'Tipo_Doc',
                'ordering': ['id'],
                'managed': False,
            },
        ),
    ]
